import { readdir, readFile, writeFile } from "fs/promises";
import { join } from "path";

const TILES_IMAGES_DIR = "src/assets/tiles-images";
const OUTPUT = "src/assets/generated.ts";

// 全てのTileCodeのリスト（裏面を含む）
const ALL_TILECODES = [
  // 萬子
  "1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
  // 筒子
  "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p",
  // 索子
  "1s", "2s", "3s", "4s", "5s", "6s", "7s", "8s", "9s",
  // 字牌
  "1z", "2z", "3z", "4z", "5z", "6z", "7z",
  // 赤ドラ
  "0m", "0p", "0s",
  // 裏面
  "back",
];

async function generateAssets() {
  try {
    const files = await readdir(TILES_IMAGES_DIR);
    const webpFiles = files.filter(f => f.endsWith(".webp"));

    const tiles: Record<string, string> = {};
    const tilesRotated: Record<string, string> = {};

    let normalCount = 0;
    let rotatedCount = 0;

    for (const file of webpFiles) {
      const filePath = join(TILES_IMAGES_DIR, file);
      const buffer = await readFile(filePath);
      const base64 = buffer.toString("base64");
      const dataUrl = `data:image/webp;base64,${base64}`;

      if (file.endsWith("-rotated.webp")) {
        // 横向き画像
        const tileCode = file.replace("-rotated.webp", "");
        tilesRotated[tileCode] = dataUrl;
        rotatedCount++;
      } else {
        // 通常画像
        const tileCode = file.replace(".webp", "");
        tiles[tileCode] = dataUrl;
        normalCount++;
      }
    }

    // 不足している牌を確認
    const missingNormal = ALL_TILECODES.filter(code => !tiles[code]);
    const missingRotated = ALL_TILECODES.filter(
      code => code !== "back" && !tilesRotated[code]
    );

    if (missingNormal.length > 0) {
      console.warn(
        `⚠️  Warning: 以下の通常画像が見つかりませんでした: ${missingNormal.join(", ")}`
      );
    }

    if (missingRotated.length > 0) {
      console.warn(
        `⚠️  Warning: 以下の横向き画像が見つかりませんでした: ${missingRotated.join(", ")}`
      );
    }

    // TypeScriptコードを生成
    const tilesEntries = Object.entries(tiles)
      .map(([code, dataUrl]) => `  '${code}': '${dataUrl}'`)
      .join(",\n");

    const tilesRotatedEntries = Object.entries(tilesRotated)
      .map(([code, dataUrl]) => `  '${code}': '${dataUrl}'`)
      .join(",\n");

    const output = `// Auto-generated by scripts/generate-webp-assets.ts - do not edit
import type { TileCode } from '../core/types'

export const tiles: Record<TileCode | 'back', string> = {
${tilesEntries}
} as const

export const tilesRotated: Partial<Record<TileCode, string>> = {
${tilesRotatedEntries}
} as const
`;

    await writeFile(OUTPUT, output);

    console.log(`✓ Generated ${normalCount} normal tiles and ${rotatedCount} rotated tiles`);
    console.log(`✓ Output: ${OUTPUT}`);

    // ファイルサイズを表示
    const stats = await readFile(OUTPUT);
    const sizeKB = (stats.length / 1024).toFixed(2);
    console.log(`✓ File size: ${sizeKB} KB`);
  } catch (error) {
    console.error("Error generating assets:", error);
    throw error;
  }
}

generateAssets().catch(console.error);
