import { readdir, readFile, writeFile } from "fs/promises";
import { join } from "path";
import { optimize } from "svgo";

const TILES_DIR = "src/assets/tiles";
const OUTPUT = "src/assets/generated.ts";

async function generate() {
  const files = await readdir(TILES_DIR);
  const entries: Record<string, string> = {};

  for (const file of files) {
    if (!file.endsWith(".svg")) continue;

    const code = file.replace(".svg", "");
    const content = await readFile(join(TILES_DIR, file), "utf-8");

    const result = optimize(content, {
      multipass: true,
      plugins: ["preset-default", "removeDimensions"],
    });

    entries[code] = result.data.replace(/'/g, "\\'");
  }

  const lines = Object.entries(entries)
    .map(([code, svg]) => `  '${code}': '${svg}'`)
    .join(",\n");

  const output = `// Auto-generated by scripts/generate-assets.ts - do not edit
import type { TileCode } from '../core/types'

export const tiles: Record<TileCode | 'back', string> = {
${lines}
} as const
`;

  await writeFile(OUTPUT, output);
  console.log(`Generated ${Object.keys(entries).length} tiles`);
}

generate().catch(console.error);
