import { readdir, readFile, writeFile } from "fs/promises";
import sharp from "sharp";
import { join } from "path";

const TILES_IMAGES_DIR = "src/assets/tiles-images";
const OUTPUT = "src/assets/generated.ts";

// 全てのTileCodeのリスト（裏面を含む）
const ALL_TILECODES = [
  // 萬子
  "1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
  // 筒子
  "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p",
  // 索子
  "1s", "2s", "3s", "4s", "5s", "6s", "7s", "8s", "9s",
  // 字牌
  "1z", "2z", "3z", "4z", "5z", "6z", "7z",
  // 赤ドラ
  "0m", "0p", "0s",
  // 裏面
  "back",
];

async function generateAssets() {
  try {
    // readdir の順序はファイルシステム依存で、そのままだと生成物の並びが環境ごとに変わる
    const files = (await readdir(TILES_IMAGES_DIR)).sort();
    const webpFiles = files.filter(f => f.endsWith(".webp"));

    const tiles: Record<string, string> = {};
    const tilesRotated: Record<string, string> = {};
    // img の width/height に出す実寸。牌ごとに違うと1つの定数で表せないので集めて検査する
    const sizes = new Set<string>();
    const rotatedSizes = new Set<string>();

    let normalCount = 0;
    let rotatedCount = 0;

    for (const file of webpFiles) {
      const filePath = join(TILES_IMAGES_DIR, file);
      const buffer = await readFile(filePath);
      const base64 = buffer.toString("base64");
      const dataUrl = `data:image/webp;base64,${base64}`;

      const { width, height } = await sharp(buffer).metadata();

      if (file.endsWith("-rotated.webp")) {
        // 横向き画像
        const tileCode = file.replace("-rotated.webp", "");
        tilesRotated[tileCode] = dataUrl;
        rotatedSizes.add(`${width}x${height}`);
        rotatedCount++;
      } else {
        // 通常画像
        const tileCode = file.replace(".webp", "");
        tiles[tileCode] = dataUrl;
        sizes.add(`${width}x${height}`);
        normalCount++;
      }
    }

    // 不足している牌を確認
    const missingNormal = ALL_TILECODES.filter(code => !tiles[code]);
    const missingRotated = ALL_TILECODES.filter(
      code => code !== "back" && !tilesRotated[code]
    );

    if (missingNormal.length > 0) {
      console.warn(
        `⚠️  Warning: 以下の通常画像が見つかりませんでした: ${missingNormal.join(", ")}`
      );
    }

    if (missingRotated.length > 0) {
      console.warn(
        `⚠️  Warning: 以下の横向き画像が見つかりませんでした: ${missingRotated.join(", ")}`
      );
    }

    // 牌ごとに寸法が違うと単一の定数では表せない。気付かず出力するより止める
    for (const [label, found] of [["通常", sizes], ["横向き", rotatedSizes]] as const) {
      if (found.size !== 1) {
        throw new Error(
          `${label}画像の寸法が揃っていません: ${[...found].join(", ")}`
        );
      }
    }
    const [tileWidth, tileHeight] = [...sizes][0].split("x");
    const [rotatedWidth, rotatedHeight] = [...rotatedSizes][0].split("x");

    // TypeScriptコードを生成
    const tilesEntries = Object.entries(tiles)
      .map(([code, dataUrl]) => `  '${code}': '${dataUrl}'`)
      .join(",\n");

    const tilesRotatedEntries = Object.entries(tilesRotated)
      .map(([code, dataUrl]) => `  '${code}': '${dataUrl}'`)
      .join(",\n");

    const output = `// Auto-generated by scripts/generate-webp-assets.ts - do not edit
import type { TileCode } from '../core/types'

export const tiles: Record<TileCode | 'back', string> = {
${tilesEntries}
} as const

export const tilesRotated: Partial<Record<TileCode, string>> = {
${tilesRotatedEntries}
} as const

export const tileSize = { width: ${tileWidth}, height: ${tileHeight} } as const

export const tileSizeRotated = { width: ${rotatedWidth}, height: ${rotatedHeight} } as const
`;

    await writeFile(OUTPUT, output);

    console.log(`✓ Generated ${normalCount} normal tiles and ${rotatedCount} rotated tiles`);
    console.log(`✓ Output: ${OUTPUT}`);

    // ファイルサイズを表示
    const stats = await readFile(OUTPUT);
    const sizeKB = (stats.length / 1024).toFixed(2);
    console.log(`✓ File size: ${sizeKB} KB`);
  } catch (error) {
    console.error("Error generating assets:", error);
    throw error;
  }
}

generateAssets().catch(console.error);
